Rename Cloud to Platform/Zeebe
camunda/bpmnlint-plugin-camunda-compat pull request #15
Opened 2022-03-17 16:06 UTC by smbea

Related to https://github.com/bpmn-io/internal-docs/issues/481

2022-03-17 16:08 UTC, MaxTru requested changes
Let's use single quotes

2022-03-17 16:10 UTC, MaxTru approved these changes

2022-03-17 16:12 UTC, MaxTru commented on rules/camunda-cloud-1-0.js
> +module.exports = createRule('Camunda Cloud', '1.0', checks, "Zeebe");
=> https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/16

2022-03-17 16:12 UTC, merged

2022-03-18 10:39 UTC, philippfromme commented on rules/utils/rule.js
> +module.exports.createRule = function(ruleExecutionPlatform, ruleExecutionPlatformVersion, checks, executionPlatformLabel) {
A test would have been nice. I will add one in the context of the current PR.